# When should this pipeline run?
# on pushes to master and PRs to master
# Note that you may not want to build packages on pull requests!
# You could also use on: release: ..., for deploying upon tagging a release.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# What jobs does this workflow consist of?
jobs:
  build:
  # Use ubuntu as an image for our build environment
    runs-on: ubuntu-latest
  # What steps does this job consist of?
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      # Setup version 12 of Java
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
    # Run all maven phases to deployment
    # with our repository as a target
      - name: Publish jar to GitHub Packages
        run: mvn deploy
        env:
          # Authenticate with GitHub using
          # token from the secrets context
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add distribution env vars
          # used in pom.xml
          DISTRIBUTION_ID: github
          DISTRIBUTION_NAME: Notes Example Project
          DISTRIBUTION_URL: https://maven.pkg.github.com/${{ github.repository }}